global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'fastapi'
    metrics_path: /metrics
    static_configs:
      - targets: ['fastapi:8000']

  - job_name: 'node'
    metrics_path: /metrics
    static_configs:
      - targets: [ 'node_exporter:9100' ]